### ISSUE TITLE
Problem with objective function in storage example

### ISSUE THREAD

**Issue by caro-rli** [oemof/oemof_base#50] opened 2016-01-11 18:23 UTC
I have taken a look at the objective function in the lp file which is generated when running the storage example (oemof_base/examples/storage_optimization). This looks very strange for me:

>min 
objective:
+50 w(pp_gas_bel_0)
+50 w(pp_gas_bel_1)
...
+50 w(pp_gas_bel_8760)
+28730000 ONE_VAR_CONSTANT

As far as I can see only opex_var (50) of the gas power plant and a constant variable is considered. What about the storage output? Why is this not part of the objective function?

Also invest variables are missing.

Does anyone know?

**Comment by simonhilpert** [comment] 2016-01-11 21:01
Yeah, this was actually due to a mixture of bug and configuration. I fixed the bug on master & dev 
and made default configuration in dev in such a way that it should work as intended. 

Note: The variable costs of the storage are only set for the storage output power. (when storing energy)

**Comment by caro-rli** [comment] 2016-01-12 13:02
Thanks!

>Note: The variable costs of the storage are only set for the storage output power. (when storing energy)

But this looks like both, storage in- and output, have variable costs
(output of storage_invest.py on current dev branch, here only for three time steps):

```
min 
objective:
+115.24258719069128 _class__oemof_core_network_entities_components_transformers_Storage___add_cap(sto_simple)
+100000000000 w(bel_sto_simple_0)
+100000000000 w(bel_sto_simple_1)
+100000000000 w(bel_sto_simple_2)
+100000000000 w(bel_sto_simple_3)
+50 w(pp_gas_bel_0)
+50 w(pp_gas_bel_1)
+50 w(pp_gas_bel_2)
+50 w(pp_gas_bel_3)
+100000000000 w(sto_simple_bel_0)
+100000000000 w(sto_simple_bel_1)
+100000000000 w(sto_simple_bel_2)
+100000000000 w(sto_simple_bel_3)
+28730000 ONE_VAR_CONSTANT
```

**Comment by simonhilpert** [comment] 2016-01-12 13:05
oh yes, your are right again...i don't know is that what you want? this functionality was not tested 
before intensively, we will have to decide how the objective has to be build.

**Comment by simonhilpert** [comment] 2016-01-12 13:09
Here is an example how you could just build an objective yourself by the use of objective expressions (the full example can be found herer: https://github.com/oemof/oemof_examples/tree/master/examples/milp_heating_system_optimization)
```python
simulation = es.Simulation(...)

simulation.objective_options['cost_objects'] = [
                                    str(cp.transformers.Simple),
                                    str(cp.transformers.VariableEfficiencyCHP),
                                    str(cp.transformers.SimpleExtractionCHP),
                                    str(cp.transformers.CHP)]

# create energysystem
energysystem = es.EnergySystem(time_idx=time_index, entities=entities,
                               simulation=simulation)
# create optimization model
energysystem.optimization_model = OM.OptimizationModel(energysystem=energysystem)


# import the objective expressiond
om = energysystem.optimization_model
from oemof.solph import objective_expressions as objexpr
# run through all cost objects and add input_costs
expr = 0
for block in simulation.objective_options['cost_objects']:
    if hasattr(om, block):
        expr += objexpr.add_input_costs(om, getattr(om, 
    # check if startup variable of block is present
        if hasattr(getattr(om,block), 'z_start'):
            expr += objexpr.add_startup_costs(om, getattr(om, block))
for block in simulation.objective_options['revenue_objects']:
    if hasattr(om, block):
        expr += objexpr.add_revenues(om, getattr(om, block))

# if there are excess or shortage costs we want to include we will use the bus block to add these costs
#expr += objexpr.add_shortage_slack_costs(om, getattr(om, str(Bus)))
expr += objexpr.add_excess_slack_costs(om, getattr(om, str(Bus)))

import pyomo.environ as po
om.objective = po.Objective(expr=expr)
```

**Comment by caro-rli** [comment] 2016-01-12 15:22
Hmm, I had a look at the predefined objective, which looks on the first sight fine for me, but somehow here (line 75)

```python
if block.optimization_options.get('investment', False):
                expr += objexpr.add_capex(self, block, ref=ref)
```

only storage investment is added, although I think everything is in the right if-loop-order.

Also variable costs for fixed sources wind and pv are not added, but here I suppose this is related to the out_max parameter, which I cannot (but would like to) omit and solph considers my fixed sources not as variables. Will do further research...

**Comment by simonhilpert** [comment] 2016-01-12 15:53
It depend which object are included in 'c_blocks' . FixedSource should be included, that is why investment costs for fixed sources should be included. But for this you need to set the following in your app: 
```python
# with this import:
from oemof.core.network.entities.components import sources as source

# statement for making FixedSource object with investment
source.FixedSource.optimization_options['investment'] = True
```

**Comment by simonhilpert** [comment] 2016-01-12 15:55
Are you sure that variable costs are not added if you set the 'opex_var'-attribute of your fixed sources?

**Comment by simonhilpert** [comment] 2016-01-12 15:57
if you want to omit out_max because your wind and pv units are calculated in investment mode you this is not possible. Then you need to set out_max equal to zero, to achieve the wanted behaviour..

**Comment by caro-rli** [comment] 2016-01-12 16:26
>But for this you need to set the following in your app

Got it. Now solph also takes right "out_max-constraint". But getting the next error..

```
  File "/home/caro/rlihome/Git/oemof_base/oemof/solph/linear_constraints.py", line 409, in invest_rule
    rhs = (out_max[e][model.O[e][0]] + model.add_out[e]) * val[e][t]
TypeError: list indices must be integers, not str
```

Also got the idea of out_max now. Same idea like cap_max for storages. We really need to think about namings, but that's offtopic here :-)

**Comment by simonhilpert** [comment] 2016-01-12 16:47
maybe the out_max causes an error. the value needs to be passed as list e.g. `out_max = [10]`. 
or val[e][t] causes an error. for a fixed source object with name 'pv' the attribute pv.val should be a simple list containing the normend pv-feed in (values between zwero and 1)

**Comment by simonhilpert** [comment] 2016-01-12 16:48
if this does not solve the problem i would need the files to reproduce the error

**Comment by caro-rli** [comment] 2016-01-12 17:04
Ok, out_max is a list, but pv.val looks like a pandas data frame. I didn't change anything here.

**Comment by caro-rli** [comment] 2016-01-12 17:06
Somehow I cannot run the storage example anymore due to import errors, so I can't provide a running file to produce the error right now.

**Comment by simonhilpert** [comment] 2016-01-12 17:21
Ok the type of `val` was ok, as it was a pd.Series but there were an error in the investment constraint.
fixed it on master and merged to dev, should work now on dev.
Thanks for reporting!

**Comment by caro-rli** [comment] 2016-01-12 17:34
Thanks for fixing!! Looks good now!

**Closed** 2016-01-18 16:27 UTC
Labels: help wanted, question
